/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type LandingPage = {
  _id: string;
  _type: "landingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageBuilder?: Array<{
    _key: string;
  } & Hero | {
    _key: string;
  } & Features | {
    _key: string;
  } & Testimonials>;
  seo?: Seo;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  siteDescription?: string;
  seo?: Seo;
  nav?: Array<{
    _key: string;
  } & Link>;
  footer?: string;
};

export type PageBuilder = Array<{
  _key: string;
} & Hero | {
  _key: string;
} & Features | {
  _key: string;
} & Testimonials>;

export type Testimonials = {
  _type: "testimonials";
  title?: string;
  items?: Array<{
    _key: string;
  } & TestimonialItem>;
};

export type TestimonialItem = {
  _type: "testimonialItem";
  quote?: string;
  authorName?: string;
  authorTitle?: string;
  authorImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Features = {
  _type: "features";
  title?: string;
  subtitle?: string;
  items?: Array<{
    _key: string;
  } & FeatureItem>;
  columns?: "2" | "3" | "4";
};

export type FeatureItem = {
  _type: "featureItem";
  title?: string;
  description?: string;
  icon?: string;
};

export type Hero = {
  _type: "hero";
  headline?: string;
  subheadline?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ctas?: Array<{
    _key: string;
  } & Link>;
  align?: "left" | "center";
};

export type Link = {
  _type: "link";
  label?: string;
  linkType?: "internal" | "external";
  internalRef?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  };
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  client?: string;
  industry?: string;
  services?: Array<string>;
  technologies?: Array<string>;
  projectUrl?: string;
  publishedAt?: string;
  seo?: Seo;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  featured?: boolean;
  aiSummary?: string;
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  role?: string;
  socialLinks?: {
    twitter?: string;
    github?: string;
    linkedin?: string;
    website?: string;
  };
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Category | LandingPage | Settings | PageBuilder | Testimonials | TestimonialItem | Features | FeatureItem | Hero | Link | CaseStudy | Post | Author | Seo | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_id == "settings"][0]{    siteName,    siteDescription,    nav[]{      label,      linkType,      externalUrl,      internalRef->{ _type, slug }    },    footer,    seo { title, description, image, noIndex }  }
export type SETTINGS_QUERYResult = {
  siteName: null;
  siteDescription: null;
  nav: null;
  footer: null;
  seo: null;
} | {
  siteName: null;
  siteDescription: null;
  nav: null;
  footer: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | null;
  } | null;
} | {
  siteName: string | null;
  siteDescription: string | null;
  nav: Array<{
    label: string | null;
    linkType: "external" | "internal" | null;
    externalUrl: string | null;
    internalRef: {
      _type: "caseStudy";
      slug: Slug | null;
    } | {
      _type: "post";
      slug: Slug | null;
    } | null;
  }> | null;
  footer: string | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;
// Variable: LANDING_PAGE_QUERY
// Query: *[_id == "landingPage"][0]{    title,    pageBuilder[]{      _key,      _type,      _type == "hero" => {        headline,        subheadline,        image {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },        align,        ctas[]{ _key, label, linkType, externalUrl, internalRef->{ _type, slug } }      },      _type == "features" => {        title,        subtitle,        columns,        items[]{ _key, title, description, icon }      },      _type == "testimonials" => {        title,        items[]{          _key,          quote,          authorName,          authorTitle,          authorImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt }        }      }    },      "seo": {    "title": coalesce(seo.title, title, ""),    "description": coalesce(seo.description, excerpt, ""),    "image": seo.image,    "noIndex": seo.noIndex == true  }  }
export type LANDING_PAGE_QUERYResult = {
  title: string | null;
  pageBuilder: null;
  seo: {
    title: string | "";
    description: string | "";
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | {
  title: null;
  pageBuilder: null;
  seo: {
    title: string | "";
    description: string | "";
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | {
  title: string | null;
  pageBuilder: null;
  seo: {
    title: string | "";
    description: "";
    image: null;
    noIndex: false;
  };
} | {
  title: null;
  pageBuilder: null;
  seo: {
    title: "";
    description: "";
    image: null;
    noIndex: false;
  };
} | {
  title: string | null;
  pageBuilder: Array<{
    _key: string;
    _type: "features";
    title: string | null;
    subtitle: string | null;
    columns: "2" | "3" | "4" | null;
    items: Array<{
      _key: string;
      title: string | null;
      description: string | null;
      icon: string | null;
    }> | null;
  } | {
    _key: string;
    _type: "hero";
    headline: string | null;
    subheadline: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: null;
    } | null;
    align: "center" | "left" | null;
    ctas: Array<{
      _key: string;
      label: string | null;
      linkType: "external" | "internal" | null;
      externalUrl: string | null;
      internalRef: {
        _type: "caseStudy";
        slug: Slug | null;
      } | {
        _type: "post";
        slug: Slug | null;
      } | null;
    }> | null;
  } | {
    _key: string;
    _type: "testimonials";
    title: string | null;
    items: Array<{
      _key: string;
      quote: string | null;
      authorName: string | null;
      authorTitle: string | null;
      authorImage: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: null;
      } | null;
    }> | null;
  }> | null;
  seo: {
    title: string | "";
    description: string | "";
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;
// Variable: POSTS_LIST_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(featured desc, publishedAt desc) [$start...$end] {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    featured,    mainImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    author->{ name, "slug": slug.current, photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt } },    categories[]->{ _id, title, "slug": slug.current }  }
export type POSTS_LIST_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  featured: boolean | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  author: {
    name: string | null;
    slug: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;
// Variable: POSTS_COUNT_QUERY
// Query: count(*[_type == "post" && defined(slug.current)])
export type POSTS_COUNT_QUERYResult = number;
// Variable: POSTS_BY_CATEGORY_QUERY
// Query: *[_type == "post" && defined(slug.current) && $categorySlug in categories[]->slug.current]  | order(publishedAt desc) [$start...$end] {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    featured,    mainImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    author->{ name, "slug": slug.current, photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt } },    categories[]->{ _id, title, "slug": slug.current }  }
export type POSTS_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  featured: boolean | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  author: {
    name: string | null;
    slug: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    featured,    mainImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    body[]{      ...,      _type == "image" => {        ...,        asset->{ _id, url, metadata { lqip, dimensions } }      }    },    author->{ _id, name, role, "slug": slug.current, photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt }, bio, socialLinks },    categories[]->{ _id, title, "slug": slug.current },    aiSummary,      "seo": {    "title": coalesce(seo.title, title, ""),    "description": coalesce(seo.description, excerpt, ""),    "image": seo.image,    "noIndex": seo.noIndex == true  }  }
export type POST_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  featured: boolean | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    role: string | null;
    slug: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: null;
    } | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    socialLinks: {
      twitter?: string;
      github?: string;
      linkedin?: string;
      website?: string;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  aiSummary: string | null;
  seo: {
    title: string | "";
    description: string | "";
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;
// Variable: CASE_STUDIES_LIST_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    client,    industry,    services,    technologies,    publishedAt,    coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt }  }
export type CASE_STUDIES_LIST_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  client: string | null;
  industry: string | null;
  services: Array<string> | null;
  technologies: Array<string> | null;
  publishedAt: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
}>;
// Variable: CASE_STUDY_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    client,    industry,    services,    technologies,    projectUrl,    publishedAt,    coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    body[]{      ...,      _type == "image" => {        ...,        asset->{ _id, url, metadata { lqip, dimensions } }      }    },      "seo": {    "title": coalesce(seo.title, title, ""),    "description": coalesce(seo.description, excerpt, ""),    "image": seo.image,    "noIndex": seo.noIndex == true  }  }
export type CASE_STUDY_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  client: string | null;
  industry: string | null;
  services: Array<string> | null;
  technologies: Array<string> | null;
  projectUrl: string | null;
  publishedAt: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
  seo: {
    title: string | "";
    description: string | "";
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)]{ "slug": slug.current }
export type CASE_STUDY_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    "postCount": count(*[_type == "post" && references(^._id)])  }
export type CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  postCount: number;
}>;
// Variable: SITEMAP_QUERY
// Query: *[_type in ["post", "caseStudy"] && defined(slug.current) && seo.noIndex != true] {    "href": select(      _type == "post" => "/blog/" + slug.current,      _type == "caseStudy" => "/case-studies/" + slug.current,      "/" + slug.current    ),    _updatedAt  }
export type SITEMAP_QUERYResult = Array<{
  href: string | null;
  _updatedAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_id == \"settings\"][0]{\n    siteName,\n    siteDescription,\n    nav[]{\n      label,\n      linkType,\n      externalUrl,\n      internalRef->{ _type, slug }\n    },\n    footer,\n    seo { title, description, image, noIndex }\n  }\n": SETTINGS_QUERYResult;
    "\n  *[_id == \"landingPage\"][0]{\n    title,\n    pageBuilder[]{\n      _key,\n      _type,\n      _type == \"hero\" => {\n        headline,\n        subheadline,\n        image { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n        align,\n        ctas[]{ _key, label, linkType, externalUrl, internalRef->{ _type, slug } }\n      },\n      _type == \"features\" => {\n        title,\n        subtitle,\n        columns,\n        items[]{ _key, title, description, icon }\n      },\n      _type == \"testimonials\" => {\n        title,\n        items[]{\n          _key,\n          quote,\n          authorName,\n          authorTitle,\n          authorImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n }\n        }\n      }\n    },\n    \n  \"seo\": {\n    \"title\": coalesce(seo.title, title, \"\"),\n    \"description\": coalesce(seo.description, excerpt, \"\"),\n    \"image\": seo.image,\n    \"noIndex\": seo.noIndex == true\n  }\n\n  }\n": LANDING_PAGE_QUERYResult;
    "\n  *[_type == \"post\" && defined(slug.current)] | order(featured desc, publishedAt desc) [$start...$end] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    featured,\n    mainImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    author->{ name, \"slug\": slug.current, photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n } },\n    categories[]->{ _id, title, \"slug\": slug.current }\n  }\n": POSTS_LIST_QUERYResult;
    "\n  count(*[_type == \"post\" && defined(slug.current)])\n": POSTS_COUNT_QUERYResult;
    "\n  *[_type == \"post\" && defined(slug.current) && $categorySlug in categories[]->slug.current]\n  | order(publishedAt desc) [$start...$end] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    featured,\n    mainImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    author->{ name, \"slug\": slug.current, photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n } },\n    categories[]->{ _id, title, \"slug\": slug.current }\n  }\n": POSTS_BY_CATEGORY_QUERYResult;
    "\n  *[_type == \"post\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    featured,\n    mainImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    body[]{\n      ...,\n      _type == \"image\" => {\n        ...,\n        asset->{ _id, url, metadata { lqip, dimensions } }\n      }\n    },\n    author->{ _id, name, role, \"slug\": slug.current, photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n }, bio, socialLinks },\n    categories[]->{ _id, title, \"slug\": slug.current },\n    aiSummary,\n    \n  \"seo\": {\n    \"title\": coalesce(seo.title, title, \"\"),\n    \"description\": coalesce(seo.description, excerpt, \"\"),\n    \"image\": seo.image,\n    \"noIndex\": seo.noIndex == true\n  }\n\n  }\n": POST_QUERYResult;
    "\n  *[_type == \"post\" && defined(slug.current)]{ \"slug\": slug.current }\n": POST_SLUGS_QUERYResult;
    "\n  *[_type == \"caseStudy\" && defined(slug.current)] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    client,\n    industry,\n    services,\n    technologies,\n    publishedAt,\n    coverImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n }\n  }\n": CASE_STUDIES_LIST_QUERYResult;
    "\n  *[_type == \"caseStudy\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    client,\n    industry,\n    services,\n    technologies,\n    projectUrl,\n    publishedAt,\n    coverImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    body[]{\n      ...,\n      _type == \"image\" => {\n        ...,\n        asset->{ _id, url, metadata { lqip, dimensions } }\n      }\n    },\n    \n  \"seo\": {\n    \"title\": coalesce(seo.title, title, \"\"),\n    \"description\": coalesce(seo.description, excerpt, \"\"),\n    \"image\": seo.image,\n    \"noIndex\": seo.noIndex == true\n  }\n\n  }\n": CASE_STUDY_QUERYResult;
    "\n  *[_type == \"caseStudy\" && defined(slug.current)]{ \"slug\": slug.current }\n": CASE_STUDY_SLUGS_QUERYResult;
    "\n  *[_type == \"category\"] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    \"postCount\": count(*[_type == \"post\" && references(^._id)])\n  }\n": CATEGORIES_QUERYResult;
    "\n  *[_type in [\"post\", \"caseStudy\"] && defined(slug.current) && seo.noIndex != true] {\n    \"href\": select(\n      _type == \"post\" => \"/blog/\" + slug.current,\n      _type == \"caseStudy\" => \"/case-studies/\" + slug.current,\n      \"/\" + slug.current\n    ),\n    _updatedAt\n  }\n": SITEMAP_QUERYResult;
  }
}
